// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: driver-service/proto/driver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to find nearby drivers
type FindNearbyDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	RadiusKm      float64                `protobuf:"fixed64,3,opt,name=radius_km,json=radiusKm,proto3" json:"radius_km,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearbyDriversRequest) Reset() {
	*x = FindNearbyDriversRequest{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearbyDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyDriversRequest) ProtoMessage() {}

func (x *FindNearbyDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyDriversRequest.ProtoReflect.Descriptor instead.
func (*FindNearbyDriversRequest) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{0}
}

func (x *FindNearbyDriversRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FindNearbyDriversRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *FindNearbyDriversRequest) GetRadiusKm() float64 {
	if x != nil {
		return x.RadiusKm
	}
	return 0
}

func (x *FindNearbyDriversRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Response with list of nearby drivers
type FindNearbyDriversResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Drivers        []*DriverInfo          `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	Count          int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	SearchRadius   float64                `protobuf:"fixed64,3,opt,name=search_radius,json=searchRadius,proto3" json:"search_radius,omitempty"`
	SearchLocation *Location              `protobuf:"bytes,4,opt,name=search_location,json=searchLocation,proto3" json:"search_location,omitempty"`
	Success        bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindNearbyDriversResponse) Reset() {
	*x = FindNearbyDriversResponse{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearbyDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearbyDriversResponse) ProtoMessage() {}

func (x *FindNearbyDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearbyDriversResponse.ProtoReflect.Descriptor instead.
func (*FindNearbyDriversResponse) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{1}
}

func (x *FindNearbyDriversResponse) GetDrivers() []*DriverInfo {
	if x != nil {
		return x.Drivers
	}
	return nil
}

func (x *FindNearbyDriversResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FindNearbyDriversResponse) GetSearchRadius() float64 {
	if x != nil {
		return x.SearchRadius
	}
	return 0
}

func (x *FindNearbyDriversResponse) GetSearchLocation() *Location {
	if x != nil {
		return x.SearchLocation
	}
	return nil
}

func (x *FindNearbyDriversResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindNearbyDriversResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Driver information
type DriverInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance      float64                `protobuf:"fixed64,5,opt,name=distance,proto3" json:"distance,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,7,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,8,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	Rating        float64                `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Geohash       string                 `protobuf:"bytes,11,opt,name=geohash,proto3" json:"geohash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverInfo) Reset() {
	*x = DriverInfo{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverInfo) ProtoMessage() {}

func (x *DriverInfo) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverInfo.ProtoReflect.Descriptor instead.
func (*DriverInfo) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DriverInfo) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DriverInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DriverInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DriverInfo) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *DriverInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverInfo) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *DriverInfo) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *DriverInfo) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *DriverInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DriverInfo) GetGeohash() string {
	if x != nil {
		return x.Geohash
	}
	return ""
}

// Location information
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Request to get driver status
type GetDriverStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverStatusRequest) Reset() {
	*x = GetDriverStatusRequest{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverStatusRequest) ProtoMessage() {}

func (x *GetDriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{4}
}

func (x *GetDriverStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

// Response with driver status
type GetDriverStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	VehicleModel  string                 `protobuf:"bytes,7,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	VehiclePlate  string                 `protobuf:"bytes,8,opt,name=vehicle_plate,json=vehiclePlate,proto3" json:"vehicle_plate,omitempty"`
	Rating        float64                `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalTrips    int32                  `protobuf:"varint,10,opt,name=total_trips,json=totalTrips,proto3" json:"total_trips,omitempty"`
	Success       bool                   `protobuf:"varint,11,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverStatusResponse) Reset() {
	*x = GetDriverStatusResponse{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverStatusResponse) ProtoMessage() {}

func (x *GetDriverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDriverStatusResponse) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{5}
}

func (x *GetDriverStatusResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetDriverStatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDriverStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDriverStatusResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetDriverStatusResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetDriverStatusResponse) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

func (x *GetDriverStatusResponse) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *GetDriverStatusResponse) GetVehiclePlate() string {
	if x != nil {
		return x.VehiclePlate
	}
	return ""
}

func (x *GetDriverStatusResponse) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetDriverStatusResponse) GetTotalTrips() int32 {
	if x != nil {
		return x.TotalTrips
	}
	return 0
}

func (x *GetDriverStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDriverStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to update driver location
type UpdateDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDriverLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Response after updating driver location
type UpdateDriverLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Geohash       string                 `protobuf:"bytes,5,opt,name=geohash,proto3" json:"geohash,omitempty"`
	Success       bool                   `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationResponse) Reset() {
	*x = UpdateDriverLocationResponse{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationResponse) ProtoMessage() {}

func (x *UpdateDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDriverLocationResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverLocationResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateDriverLocationResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateDriverLocationResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UpdateDriverLocationResponse) GetGeohash() string {
	if x != nil {
		return x.Geohash
	}
	return ""
}

func (x *UpdateDriverLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDriverLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request to update driver status
type UpdateDriverStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // AVAILABLE, BUSY, OFFLINE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverStatusRequest) Reset() {
	*x = UpdateDriverStatusRequest{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverStatusRequest) ProtoMessage() {}

func (x *UpdateDriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDriverStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Response after updating driver status
type UpdateDriverStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverStatusResponse) Reset() {
	*x = UpdateDriverStatusResponse{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverStatusResponse) ProtoMessage() {}

func (x *UpdateDriverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverStatusResponse) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDriverStatusResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDriverStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UpdateDriverStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateDriverStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{10}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_driver_service_proto_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_service_proto_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_driver_service_proto_driver_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_driver_service_proto_driver_proto protoreflect.FileDescriptor

const file_driver_service_proto_driver_proto_rawDesc = "" +
	"\n" +
	"!driver-service/proto/driver.proto\x12\x06driver\"\x87\x01\n" +
	"\x18FindNearbyDriversRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tradius_km\x18\x03 \x01(\x01R\bradiusKm\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xf3\x01\n" +
	"\x19FindNearbyDriversResponse\x12,\n" +
	"\adrivers\x18\x01 \x03(\v2\x12.driver.DriverInfoR\adrivers\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12#\n" +
	"\rsearch_radius\x18\x03 \x01(\x01R\fsearchRadius\x129\n" +
	"\x0fsearch_location\x18\x04 \x01(\v2\x10.driver.LocationR\x0esearchLocation\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\xca\x02\n" +
	"\n" +
	"DriverInfo\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x05 \x01(\x01R\bdistance\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rvehicle_plate\x18\a \x01(\tR\fvehiclePlate\x12#\n" +
	"\rvehicle_model\x18\b \x01(\tR\fvehicleModel\x12\x16\n" +
	"\x06rating\x18\t \x01(\x01R\x06rating\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\x12\x18\n" +
	"\ageohash\x18\v \x01(\tR\ageohash\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"5\n" +
	"\x16GetDriverStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"\xff\x02\n" +
	"\x17GetDriverStatusResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12%\n" +
	"\x0elicense_number\x18\x06 \x01(\tR\rlicenseNumber\x12#\n" +
	"\rvehicle_model\x18\a \x01(\tR\fvehicleModel\x12#\n" +
	"\rvehicle_plate\x18\b \x01(\tR\fvehiclePlate\x12\x16\n" +
	"\x06rating\x18\t \x01(\x01R\x06rating\x12\x1f\n" +
	"\vtotal_trips\x18\n" +
	" \x01(\x05R\n" +
	"totalTrips\x12\x18\n" +
	"\asuccess\x18\v \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\"t\n" +
	"\x1bUpdateDriverLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"\xe1\x01\n" +
	"\x1cUpdateDriverLocationResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\ageohash\x18\x05 \x01(\tR\ageohash\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\"P\n" +
	"\x19UpdateDriverStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa3\x01\n" +
	"\x1aUpdateDriverStatusResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"\x7f\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xc5\x03\n" +
	"\rDriverService\x12X\n" +
	"\x11FindNearbyDrivers\x12 .driver.FindNearbyDriversRequest\x1a!.driver.FindNearbyDriversResponse\x12R\n" +
	"\x0fGetDriverStatus\x12\x1e.driver.GetDriverStatusRequest\x1a\x1f.driver.GetDriverStatusResponse\x12a\n" +
	"\x14UpdateDriverLocation\x12#.driver.UpdateDriverLocationRequest\x1a$.driver.UpdateDriverLocationResponse\x12[\n" +
	"\x12UpdateDriverStatus\x12!.driver.UpdateDriverStatusRequest\x1a\".driver.UpdateDriverStatusResponse\x12F\n" +
	"\vHealthCheck\x12\x1a.driver.HealthCheckRequest\x1a\x1b.driver.HealthCheckResponseB\tZ\a./protob\x06proto3"

var (
	file_driver_service_proto_driver_proto_rawDescOnce sync.Once
	file_driver_service_proto_driver_proto_rawDescData []byte
)

func file_driver_service_proto_driver_proto_rawDescGZIP() []byte {
	file_driver_service_proto_driver_proto_rawDescOnce.Do(func() {
		file_driver_service_proto_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_service_proto_driver_proto_rawDesc), len(file_driver_service_proto_driver_proto_rawDesc)))
	})
	return file_driver_service_proto_driver_proto_rawDescData
}

var file_driver_service_proto_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_driver_service_proto_driver_proto_goTypes = []any{
	(*FindNearbyDriversRequest)(nil),     // 0: driver.FindNearbyDriversRequest
	(*FindNearbyDriversResponse)(nil),    // 1: driver.FindNearbyDriversResponse
	(*DriverInfo)(nil),                   // 2: driver.DriverInfo
	(*Location)(nil),                     // 3: driver.Location
	(*GetDriverStatusRequest)(nil),       // 4: driver.GetDriverStatusRequest
	(*GetDriverStatusResponse)(nil),      // 5: driver.GetDriverStatusResponse
	(*UpdateDriverLocationRequest)(nil),  // 6: driver.UpdateDriverLocationRequest
	(*UpdateDriverLocationResponse)(nil), // 7: driver.UpdateDriverLocationResponse
	(*UpdateDriverStatusRequest)(nil),    // 8: driver.UpdateDriverStatusRequest
	(*UpdateDriverStatusResponse)(nil),   // 9: driver.UpdateDriverStatusResponse
	(*HealthCheckRequest)(nil),           // 10: driver.HealthCheckRequest
	(*HealthCheckResponse)(nil),          // 11: driver.HealthCheckResponse
}
var file_driver_service_proto_driver_proto_depIdxs = []int32{
	2,  // 0: driver.FindNearbyDriversResponse.drivers:type_name -> driver.DriverInfo
	3,  // 1: driver.FindNearbyDriversResponse.search_location:type_name -> driver.Location
	0,  // 2: driver.DriverService.FindNearbyDrivers:input_type -> driver.FindNearbyDriversRequest
	4,  // 3: driver.DriverService.GetDriverStatus:input_type -> driver.GetDriverStatusRequest
	6,  // 4: driver.DriverService.UpdateDriverLocation:input_type -> driver.UpdateDriverLocationRequest
	8,  // 5: driver.DriverService.UpdateDriverStatus:input_type -> driver.UpdateDriverStatusRequest
	10, // 6: driver.DriverService.HealthCheck:input_type -> driver.HealthCheckRequest
	1,  // 7: driver.DriverService.FindNearbyDrivers:output_type -> driver.FindNearbyDriversResponse
	5,  // 8: driver.DriverService.GetDriverStatus:output_type -> driver.GetDriverStatusResponse
	7,  // 9: driver.DriverService.UpdateDriverLocation:output_type -> driver.UpdateDriverLocationResponse
	9,  // 10: driver.DriverService.UpdateDriverStatus:output_type -> driver.UpdateDriverStatusResponse
	11, // 11: driver.DriverService.HealthCheck:output_type -> driver.HealthCheckResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_driver_service_proto_driver_proto_init() }
func file_driver_service_proto_driver_proto_init() {
	if File_driver_service_proto_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_service_proto_driver_proto_rawDesc), len(file_driver_service_proto_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_service_proto_driver_proto_goTypes,
		DependencyIndexes: file_driver_service_proto_driver_proto_depIdxs,
		MessageInfos:      file_driver_service_proto_driver_proto_msgTypes,
	}.Build()
	File_driver_service_proto_driver_proto = out.File
	file_driver_service_proto_driver_proto_goTypes = nil
	file_driver_service_proto_driver_proto_depIdxs = nil
}
